### ISSUE TITLE
release artifacts for tag 0.1

### ISSUE THREAD

**Issue by gliptak** [f5devcentral/terraform-provider-bigip#13]
The Travis build is already configured to release on tagging:

https://github.com/f5devcentral/terraform-provider-f5/blob/d1f2e27dbb991f9f5496278bfd4db1765b7754e1/.travis.yml#L40

Could you tag ```0.1``` (to validate the key and the process)?

Thanks

**Comment by gliptak** [comment]
@scshitole Please comment. Thanks

**Comment by scshitole** [comment]
@gliptak  I pushed the tag 0.1

**Comment by gliptak** [comment]
Ok, you released files at https://github.com/f5devcentral/terraform-provider-bigip/releases

But the build throw an error https://travis-ci.org/f5devcentral/terraform-provider-bigip/builds/299245385

```
No stash entries found.

/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:19:in `get'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/users.rb:34:in `user'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider/releases.rb:48:in `user'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider/releases.rb:73:in `setup_auth'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider/releases.rb:77:in `check_auth'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider.rb:142:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider.rb:141:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```
Try updating the deploy key at
https://github.com/f5devcentral/terraform-provider-bigip/blob/c0462d873159fce92b9fbbf4073a053e9e6b8f46/.travis.yml#L39

**Comment by gliptak** [comment]
https://elithrar.github.io/article/build-go-binaries-travis-ci-github/

**Comment by scshitole** [comment]
https://github.com/f5devcentral/terraform-provider-bigip/releases
